### ISSUE TITLE
Info box

### ISSUE THREAD

**Issue by m-lant** [rceuls/janus#4]
"Gemakkelijke" manier om die info in te laden aub. Komt ongetwijfeld uit excel of ne google Sheet, dus idk, ne csv?

Info:

- [x] Code: 3 alfanumerieke karakters, optioneel
- [x] Coördinaten (hidden), verplicht als er een code is => bolletje met code op de kaart
- [x] Locatie: tekst
- [x] Organisatie: tekst
- [x] Werk-uren
- [x] Verantwoordelijke: tekst
- [x] Verantwoordelijke tel. nr: tekst
- [x] Verantwoordelijke bereikbaarheid: tekst
- [x] Er kunnen meerdere verantwoordelijken zijn
- [x] Oproepnaam

Zie "bolletjesplan" met tabel rechts voor voorbeelden.

**Comment by rceuls** [comment]
Developed an ddeployed on trunk
